# Generated by Django 5.2.6 on 2025-11-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20251113_1132'),
    ]

    operations = [
    ]
