# Generated by Django 5.2.6 on 2025-12-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.FloatField(default=0.0)),
                ('employees_active', models.IntegerField(default=0)),
                ('receivables', models.FloatField(default=0.0)),
                ('cash_balance', models.FloatField(default=0.0)),
                ('month', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
