# Generated by Django 5.2.6 on 2025-12-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('due', models.DateField(blank=True, null=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
