# Generated by Django 5.2.6 on 2025-12-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('party_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tx_type', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('PAYMENT_IN', 'Payment Received'), ('PAYMENT_OUT', 'Payment Made')], max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CARD', 'Card'), ('OTHER', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
