# Generated by Django 5.2.6 on 2025-12-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('LEAD', 'Lead'), ('CLIENT', 'Client'), ('PROJECT', 'Project'), ('ASSIGNMENT', 'Assignment'), ('CALLLOG', 'Call Log'), ('FOLLOWUP', 'Follow Up')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('given_on', models.DateField(auto_now_add=True)),
                ('submission_date', models.DateField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-given_on', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
