# Generated by Django 5.2.6 on 2025-12-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_workgiven_delete_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workgiven',
            options={},
        ),
        migrations.RemoveField(
            model_name='workgiven',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='workgiven',
            name='entity_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='access_level',
            field=models.CharField(default='Executive', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='role_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='workgiven',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.employee'),
        ),
        migrations.AddField(
            model_name='workgiven',
            name='priority',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='workgiven',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workgiven',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
