# Generated by Django 5.2.6 on 2025-12-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_employee_address_employee_city_employee_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='follow_up',
            field=models.BooleanField(default=False),
        ),
    ]
