# Generated by Django 5.2.6 on 2025-12-16 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_calllog_follow_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='crm.employee'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='is_missed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
