# Generated by Django 5.2.6 on 2025-12-17 11:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_calllog_assigned_calllog_is_missed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={},
        ),
        migrations.RenameField(
            model_name='calllog',
            old_name='note',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='calllog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calllog',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.client'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calllog',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
